[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  base = "frontend"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://feelwrite-622255484144.us-central1.run.app"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin, X-CSRF-Token"
    Access-Control-Max-Age = "86400"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin, X-CSRF-Token"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  included_files = [
    "node_modules/@netlify/plugin-nextjs/**/*",
    "node_modules/next/**/*",
    "node_modules/react/**/*",
    "node_modules/react-dom/**/*"
  ]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs", "next", "react", "react-dom"]

[build.processing]
  skip_processing = true
